version: '3.8'
services:
  interview-app:
    image: interview-app:latest
    container_name: interview-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      # 数据库配置
      - MYSQL_JDBC_URL=jdbc:mysql://your-mysql-host:3306/yourdb?useSSL=false&serverTimezone=UTC
      - MYSQL_USERNAME=your_db_user
      - MYSQL_PASSWORD=your_db_password
      # Redis配置
      - REDIS_HOST=your-redis-host
      - REDIS_PASSWORD=your_redis_password
      # 其他如MinIO、AI服务等可按需添加
      # - MINIO_ENDPOINT=your-minio-endpoint
      # - MINIO_ACCESS_KEY=your-minio-access-key
      # - MINIO_SECRET_KEY=your-minio-secret-key
    restart: unless-stopped
    # 可选：如需挂载日志或上传目录
    # volumes:
    #   - ./logs:/app/logs
    #   - ./resumeUploads:/app/resumeUploads 